import { createFileRoute,Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useSession } from '@/lib/use-session';
import { Button } from '@/components/ui/button';
import { pageHead,money,storeQuery,type Order } from '@/lib/store';
import { toast } from 'sonner';
import { CatalogueEditor } from '@/components/catalogue-editor';
export const Route=createFileRoute('/staff')({head:()=>pageHead('Staff dashboard','Restricted order verification and store management.'),component:Staff});
function Staff(){const {session,loading}=useSession(),[tab,setTab]=useState('orders'),[filter,setFilter]=useState('');const role=useQuery({queryKey:['staff-role',session?.user.id],enabled:!!session,queryFn:async()=>{const {data,error}=await supabase.rpc('is_staff');if(error)throw error;return data;}});const orders=useQuery({queryKey:['staff-orders',session?.user.id],enabled:role.data===true,queryFn:async()=>{const {data,error}=await supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;return data;}});const store=useQuery(storeQuery);
 if(loading||role.isLoading)return <div className="page-content wrap">Checking access…</div>;if(!session||!role.data)return <div className="page-content wrap"><h1 className="page-title">Staff access</h1><p className="page-lead">{session?'Your account does not have staff permission. Ask the store owner to grant access.':'Sign in with your staff account to verify payments and manage orders.'}</p><Button asChild className="mt-6"><Link to="/account">Go to account</Link></Button></div>;
 return <div className="page-content wrap"><h1 className="page-title">Store dashboard</h1><p className="page-lead">Verify Mobile Money against the provider's transaction record before confirming payment.</p><div className="my-7 flex gap-3">{['orders','inventory','settings'].map(t=><Button key={t} variant={tab===t?'default':'outline'} onClick={()=>setTab(t)} className="capitalize">{t}</Button>)}</div>{tab==='orders'&&<><input aria-label="Filter orders" className="mb-5 max-w-md" placeholder="Search reference, customer or MoMo reference" value={filter} onChange={e=>setFilter(e.target.value)}/>{orders.isError?<p role="alert">Orders could not load.</p>:orders.data?.length?orders.data.filter(o=>`${o.reference} ${o.customer_name} ${o.transaction_reference}`.toLowerCase().includes(filter.toLowerCase())).map(o=><StaffOrder key={o.id} order={o} refresh={()=>orders.refetch()}/>):<p className="text-muted-foreground">No orders yet. New orders will appear here.</p>}</>}{tab==='inventory'&&store.data&&<CatalogueEditor products={store.data.products} categories={store.data.categories} refresh={()=>store.refetch()}/>}{tab==='settings'&&store.data&&<form className="max-w-xl space-y-4" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const enabled=f.get('enabled')==='on';if(enabled&&(!f.get('momo_number')||!f.get('momo_name'))){toast.error('Enter verified Mobile Money recipient details first.');return;}const {error}=await supabase.from('store_settings').update({phone:String(f.get('phone')),email:String(f.get('email')),address:String(f.get('address')),hours:String(f.get('hours')),momo_number:String(f.get('momo_number')),momo_name:String(f.get('momo_name')),ordering_enabled:enabled}).eq('id',1);if(error)toast.error(error.message);else {toast.success('Store settings saved');store.refetch();}}}>{(['phone','email','address','hours','momo_number','momo_name'] as const).map(k=><label key={k} className="capitalize">{k.replaceAll('_',' ')}<input name={k} defaultValue={String(store.data!.settings[k])}/></label>)}<label className="filter-line"><input name="enabled" type="checkbox" defaultChecked={store.data.settings.ordering_enabled}/>Open ordering after verifying inventory and recipient details</label><Button>Save settings</Button></form>}</div>;
}
function StaffOrder({order:o,refresh}:{order:Order;refresh:()=>void}){const [status,setStatus]=useState(o.status),[payment,setPayment]=useState(o.payment_status),[busy,setBusy]=useState(false);return <article className="solid-panel mb-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-mono text-lg">{o.reference}</h2><span>{money(o.total,true)}</span></div><p className="mt-3 text-sm">{o.customer_name} · {o.phone} · {o.email}</p><p className="mt-2 text-xs text-muted-foreground">{o.fulfillment==='pickup'?'Circle pickup':o.address} · {new Date(o.created_at).toLocaleString()}</p><p className="mt-4 text-sm font-semibold">{o.payment_method==='momo'?`${o.provider} · Transaction: ${o.transaction_reference}`:'Cash on delivery · Confirm cash collection after courier arrival'}</p><div className="mt-5 grid gap-4 sm:grid-cols-3"><label>Order status<select value={status} onChange={e=>setStatus(e.target.value)}>{['received','processing',...(o.fulfillment==='pickup'?['ready']:['dispatched']),'completed','cancelled'].map(s=><option key={s}>{s}</option>)}</select></label><label>Payment status<select value={payment} onChange={e=>setPayment(e.target.value)}>{['pending','confirmed','rejected'].map(s=><option key={s}>{s}</option>)}</select></label><Button className="self-end" disabled={busy} onClick={async()=>{if(payment==='confirmed'&&o.payment_status!=='confirmed'&&!window.confirm(o.payment_method==='momo'?'Have you verified the transaction and amount in the provider record?':'Has the courier confirmed cash collection?'))return;setBusy(true);const {error}=await supabase.rpc('staff_update_order',{order_uuid:o.id,new_status:status,new_payment:payment});if(error)toast.error(error.message);else {toast.success('Order updated');refresh();}setBusy(false);}}>Save update</Button></div></article>;}
